### ISSUE TITLE
Problem running test Suite on Windows 10 with Python3

### ISSUE THREAD

**Issue by MadraghRua** [llotneb/SBOL#60]
Hi Folks
I cloned and imported SBOL into ActivePython 3.6.6. Import appears to work ad I can use help(sbol) to get a list of the package contents and functions. 
I tried out the test scripts from the ReadMe. I get the following error message:
>>>import sbol
>>> sbol.testSBOL()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\myuser\documents\github\pysbol\sbol\sbol\__init__.py", line 35, in testSBOL
    import sbol.test as unit_tests
  File "c:\users\myuser\documents\github\pysbol\sbol\sbol\test\__init__.py", line 15, in <module>
    from .test_roundtrip import TestRoundTripSBOL2, TestRoundTripFailSBOL2
  File "c:\users\myuser\documents\github\pysbol\sbol\sbol\test\test_roundtrip.py", line 14, in <module>
    FILES_SBOL2 = os.listdir(TEST_LOC_SBOL2)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\myuser\\documents\\github\\pysbol\\sbol\\sbol\\test\\SBOLTestSuite\\SBOL2'

I notice in the file paths that it is not not retaining capitalization used in the folder names (eg user should be Users, documents should be Documents, etc). What should I try next to correct this?
Thanks!

**Comment by bbartley** [comment]
Hi @MadraghRua I suspect this is actually a git problem rather than a pySBOL problem.  The SBOLTestSuite is incorporated as a git submodule, which doesn't get cloned automatically.

If you have already cloned the project, you can use:
```
git submodule init
git submodule update
```
Or if you are cloning the pySBOL repo from scratch, you can try
```
git clone --recursive YOUR-GIT-REPO-URL
```
I think this should solve the FileNotFound errors

**Comment by tcmitchell** [comment]
We've got an outstanding task to add those instructions to the documentation. See #12 

Sorry about that!

**Comment by MadraghRua** [comment]
That's fine. I followed your instructions and was able to run the two test scripts. The major thing from that is the overwhelming number of messages like this:
WARNING:rdflib.term:http://my_namespace.org\Range\example\1 does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://my_namespace.org\example does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://my_namespace.org\example does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://my_namespace.org\example does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://my_namespace.org\SequenceAnnotation\example\1 does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://my_namespace.org\SequenceAnnotation\example\1 does not look like a valid URI, trying to serialize this will break.
ok

This is effectively swamping out any reporting that the test suites have. 
Thanks!

**Comment by tcmitchell** [comment]
@MadraghRua actually, this looks like a bug that manifests on the windows platform. When I look at a [recent build on Travis](https://travis-ci.com/llotneb/SBOL/jobs/281949942) I see two occurrences of this warning. Certainly not enough to swamp out the reporting in the test suites. 

The URL you show above is `http://my_namespace.org\SequenceAnnotation\example\1` and has backslashes instead of forward slashes. We would expect `http://my_namespace.org/SequenceAnnotation/example/1` instead. See the difference?

This is caused by using `os.path.join` to append URI elements together. That works fine on Unix and MacOS, but fails on Windows. URIs and URLs should not be joined together with os.path.join. Or may need correction after joining that way.

Is it ok if we change the title on this issue to be specific to this path joining issue on Windows platforms?

**Comment by tcmitchell** [comment]
@MadraghRua can you post the summary of the two test suite runs? It looks to me like we have tests that should be failing given what you've posted above. Did the tests say "OK" at the end? Or did the tests report any failures?

I'd be expecting something along the lines of:

```
----------------------------------------------------------------------
Ran 77 tests in 12.417s

FAILED (failures=1, skipped=1, expected failures=8)
```

And not:

```
----------------------------------------------------------------------
Ran 77 tests in 10.752s

OK (skipped=1, expected failures=8)
```

Please post the output you're getting.
